- src/Data/MessagePack/Types/Generic.hs
Issue #2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-msgpack-types/3)
> Change generic empty ADT constructor serialization to [code]

- .leaf.yml
- .travis.yml
- appveyor.yml
- src/Data/MessagePack/Types/Object.hs
- stack.yaml
- test/Data/MessagePack/OptionSpec.hs
- test/Data/MessagePack/ResultSpec.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-msgpack-types/10)
> Build with `stack` instead of `cabal` on Travis.

- data-msgpack-types.cabal
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-msgpack-types/11)
> Release v0.0.2.

- .travis.yml
- BUILD.bazel
- LICENSE
- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-msgpack-types/14)
> Enable .travis.yml check and use non-markdown license.

- BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-msgpack-types/15)
> Hook up the tests to the bazel build.

- appveyor.yml
- stack.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-msgpack-types/17)
> Format yaml files according to yamllint's requirements.

- src/Data/MessagePack/Types/Class.hs
- src/Data/MessagePack/Types/Generic.hs
- src/Data/MessagePack/Types/Option.hs
- src/Data/MessagePack/Types/Result.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-msgpack-types/19)
> Support GHC 8.8

- BUILD.bazel
- appveyor.yml
- data-msgpack-types.cabal
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-msgpack-types/21)
> Use new rules_haskell name for bazel 2.1.1.

- .travis.yml
toktok-releaser changed its token.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-msgpack-types/26)
> Update github token.

- .travis.yml
This should push new releases to hackage via travis deploy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-msgpack-types/28)
> Enable stack upload on tags.

- BUILD.bazel
- test/Data/MessagePack/Types/ClassSpec.hs
This is becoming the default.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-msgpack-types/32)
> Remove standard_travis setting in BUILD.bazel.

- .cirrus.yml
- .github/workflows/ci.yml
Not on pull requests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-msgpack-types/44)
> chore: Only try publishing hackage candidates on push.

- .cirrus.yml
- BUILD.bazel
- msgpack-types.cabal
- src/Data/MessagePack/Types/Generic.hs
- stack.yaml
fixes https://github.com/TokTok/hs-msgpack-binary/issues/75
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-msgpack-types/34)
> fix: translate type products as linear arrays

- .cirrus.yml
- .github/settings.yml
- .github/workflows/checks.yml
- .github/workflows/ci.yml
- .github/workflows/publish.yml
- BUILD.bazel
- msgpack-types.cabal
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-msgpack-types/47)
> chore: Use centralised workflows for CI.

- .cirrus.yml
- .github/settings.yml
- .github/workflows/publish.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-msgpack-types/48)
> chore: Upgrade to latest toktok-stack

- .github/docker/Dockerfile
- .github/settings.yml
- .github/workflows/publish.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-msgpack-types/50)
> chore: Use the docker image for CI builds.

- BUILD.bazel
- msgpack-types.cabal
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-msgpack-types/56)
> chore: Add missing file to .cabal.

- src/Data/MessagePack/Types/Object.hs
- test/Data/MessagePack/Arbitrary.hs
- test/Data/MessagePack/Types/ClassSpec.hs
Reducing dependencies.
Fixes https://github.com/TokTok/hs-msgpack-types/issues/31.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-msgpack-types/58)
> cleanup: Remove Arbitrary instance from main library.

- BUILD.bazel
- msgpack-types.cabal
- src/Data/MessagePack/Tags.hs
- tools/gen-tags
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-msgpack-types/60)
> cleanup: Generate tag patterns from the official docs.

- msgpack-types.cabal
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/toktok/hs-msgpack-types/62)
> chore: Add missing test module to cabal.

- .cirrus.yml
- BUILD.bazel
- src/Data/MessagePack/Types.hs
- src/Data/MessagePack/Types/Assoc.hs
- src/Data/MessagePack/Types/Class.hs
- src/Data/MessagePack/Types/DecodeError.hs
- src/Data/MessagePack/Types/Generic.hs
- src/Data/MessagePack/Types/Object.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-msgpack-types/67)
> chore: Update to new third_party method for haskell deps.

- src/Data/MessagePack/Tags.hs
- tools/gen-tags
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-msgpack-types/68)
> cleanup: Suppress another ghc warning in generated tags file.

- BUILD.bazel
- test/Data/MessagePack/Types/AssocSpec.hs
- test/Data/MessagePack/Types/ClassSpec.hs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-msgpack-types/69)
> chore: Remove warning suppression.

- BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/TokTok/hs-msgpack-types/73)
> chore: Add more descriptive/precise tags to bazel build rules.
